### PR TITLE
Add layout features and webslides

### PR DESCRIPTION
**Pull request by iafb**
- Add features to layout pages
- Add webslides to layout pages

### CODE REVIEW

**Review by k7hpn — APPROVED** [review]

**Comment by k7hpn** [comment]
@iafb I've made significant changes to this PR, please review and let me know if you think it looks good

**Comment by iafb** [comment]
@k7hpn I noticed a couple things going through it

- Feature Images aren't displaying on the Promenade page, image upload seems to have changed to save images into an Ops folder instead of the Promenade public folder
- There's a difference in how cloning layout pages functions for segments and image features, segments items have a new segment created while image features have the same feature linked to the new layout
- In Ops, Image Feature details page uses the term "Feature" on the header and in the image upload tool-tip when viewing a Webslide, with the model consolidation I'm not sure if we're still splitting terminology or using the same term for both.

**Comment by k7hpn** [comment]
> Feature Images aren't displaying on the Promenade page, image upload seems to have changed to save images into an Ops folder instead of the Promenade public folder

These files should be placed in the directory specified by Ops site setting `SiteManagement.PromenadePublicPath`

> There's a difference in how cloning layout pages functions for segments and image features, segments items have a new segment created while image features have the same feature linked to the new layout

Correct.

> In Ops, Image Feature details page uses the term "Feature" on the header and in the image upload tool-tip when viewing a Webslide, with the model consolidation I'm not sure if we're still splitting terminology or using the same term for both.

I'll fix this to be "Image Feature".

**Comment by iafb** [comment]
> 
> 
> > Feature Images aren't displaying on the Promenade page, image upload seems to have changed to save images into an Ops folder instead of the Promenade public folder
> 
> These files should be placed in the directory specified by Ops site setting `SiteManagement.PromenadePublicPath`
> 

Ah right, my bad on that one. Everything else looks like it should be good.

**Pull request merged**
